<?xml version="1.0"?>
<robot name="new_car" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- Properties -->
    <xacro:property name="base_width" value="1.041"/>
    <xacro:property name="base_length" value="1.892"/>
    <xacro:property name="base_height" value="0.626"/>
    <xacro:property name="wheel_radius" value="0.191"/>
    <xacro:property name="wheel_width" value="0.121"/>
    <xacro:property name="wheel_ygap" value="-0.06"/>
    <xacro:property name="wheel_zoff" value="0.123"/>
    <xacro:property name="wheel_xoff" value="0.756"/>

    <!-- Inertia Macros -->
    <xacro:macro name="box_inertia" params="m w h d">
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" 
                     iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy="0" ixz="0" 
                     iyy="${(m/12) * (3*r*r + h*h)}" iyz="0" izz="${(m/2) * (r*r)}"/>
        </inertial>
    </xacro:macro>

    <!-- Robot Base -->
    <link name="base_link">
        <visual>
            <origin xyz=".946 .521 -.313" rpy="0 0 ${pi}"/>
            <geometry>
                <mesh filename="package://agv_car_gazebo/models/agv_car/meshes/agv_chassis.stl"/>
            </geometry>
            <material name="Cyan">
                <color rgba="0 1.0 1.0 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://agv_car_gazebo/models/agv_car/meshes/agv_chassis.stl"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>
    </link>

    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 ${-(wheel_radius + wheel_zoff)}" rpy="0 0 0"/>
    </joint>

    <!-- Wheel Macro -->
    <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="Gray">
                    <color rgba="0.5 0.5 0.5 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
        </link>

        <joint name="${prefix}_wheel_joint" type="revolute">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="${x_reflect * wheel_xoff} ${y_reflect * (base_width/2 + wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <limit effort="1000.0" lower="-0.698" upper="0.698" velocity="0.5"/>
        </joint>
    </xacro:macro>

    <!-- Steering Wheel Macro -->
    <xacro:macro name="steering_wheel" params="prefix x_reflect y_reflect">
        <link name="${prefix}_steering_wheel">
            <visual>
                <origin xyz="0.05 ${y_reflect * (wheel_width / 2 - .1)} 0" rpy="${pi/2} ${pi/2} 0"/>
                <geometry>
                    <cylinder radius="0.03" length="0.1"/>
                </geometry>
                <material name="Gray">
                    <color rgba="0.5 0.5 0.5 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 -0 0"/>
                <geometry>
                    <cylinder radius="0.03" length="0.1"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="0.5" r="0.03" h="0.1"/>
        </link>

        <joint name="${prefix}_steering_joint" type="revolute">
            <parent link="base_link"/>
            <child link="${prefix}_steering_wheel"/>
            <origin xyz="${x_reflect * wheel_xoff} ${y_reflect * (base_width / 2 + wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <limit effort="1000.0" lower="-0.698" upper="0.698" velocity="0.5"/>
        </joint>
    </xacro:macro>

    <!-- Front and Rear Wheels -->
    <xacro:wheel prefix="rear_left" x_reflect="-1" y_reflect="1"/>
    <xacro:wheel prefix="rear_right" x_reflect="-1" y_reflect="-1"/>
    <xacro:steering_wheel prefix="front_left" x_reflect="1" y_reflect="1"/>
    <xacro:steering_wheel prefix="front_right" x_reflect="1" y_reflect="-1"/>

    <!-- Ackermann Steering Plugin -->
    <plugin filename="gz-sim-ackermann-steering" name="gz::sim::systems::AckermannSteering">
        <left_joint>rear_left_wheel_joint</left_joint>
        <right_joint>rear_right_wheel_joint</right_joint>
        <front_left_joint>front_left_steering_joint</front_left_joint>
        <front_right_joint>front_right_steering_joint</front_right_joint>
        <wheel_separation>0.287</wheel_separation>
        <wheel_radius>${wheel_radius}</wheel_radius>
        <max_linear_acceleration>0.033</max_linear_acceleration>
        <topic>cmd_vel</topic>
        <odom_topic>odom</odom_topic>
        <frame_id>odom</frame_id>
        <child_frame_id>base_footprint</child_frame_id>
        <odom_publisher_frequency>30</odom_publisher_frequency>
        <tf_topic>/tf</tf_topic>
    </plugin>

</robot>
