<?xml version="1.0"?>
<robot name="new_car" xmlns:xacro="http://ros.org/wiki/xacro">  
    <!-- <xacro:include filename="colors.xacro" /> -->
    <xacro:include filename="inertial_macros.xacro" />

    <xacro:property name="base_width" value="1.041"/>
    <xacro:property name="base_length" value="1.892"/>
    <xacro:property name="base_height" value="0.626"/>

    <xacro:property name="wheel_radius" value="0.191"/>
    <xacro:property name="wheel_width" value="0.121"/>
    <xacro:property name="wheel_ygap" value="-0.06"/>
    <xacro:property name="wheel_zoff" value="0.123"/>
    <xacro:property name="wheel_xoff" value="0.756"/>

    <!-- Robot Base -->
    <link name="base_link">
        <visual>
            <origin xyz=".946 .521 -0.313" rpy="0 0 ${pi}" />
            <geometry>
                <mesh filename="package://agv_car_gazebo/models/agv_car/meshes/agv_chassis.stl"/>
            </geometry>
            <material name="Cyan">
                <color rgba="0 1.0 1.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz=".946 .521 -0.313" rpy="0 0 ${pi}" />
            <geometry>
                <mesh filename="package://agv_car_gazebo/models/agv_car/meshes/agv_chassis.stl"/>
            </geometry>
        </collision>


        <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>
    </link>

    <!-- Robot Footprint -->
    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
    </joint>

    <!-- Wheels -->
    <xacro:macro name="rearwheel" params="prefix x_reflect y_reflect">
        <link name="rear_${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="Gray">
                    <color rgba="0.5 0.5 0.5 1.0"/>
                </material>
            </visual>
            <collision>
                <!-- <origin xyz="0 0 0" rpy="${pi/2} 0 0"/> -->
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>

            <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
        </link>

        <joint name="rear_${prefix}_wheel_joint" type="revolute">
            <parent link="base_link"/>
            <child link="rear_${prefix}_wheel"/>
            <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} 0" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <limit effort="1000.0" lower="-0.698" upper="0.698" velocity="0.5"/>
        </joint>
    </xacro:macro>

    <xacro:rearwheel prefix="left" x_reflect="-1" y_reflect="1"/>
    <xacro:rearwheel prefix="right" x_reflect="-1" y_reflect="-1"/>

    <!-- Steering Wheels -->
    <xacro:macro name="steering_wheel" params="prefix x_reflect y_reflect">
        <link name="front_${prefix}_steering_wheel_link">
            <visual>
                <origin xyz="0.05 ${y_reflect * (wheel_width / 2 - .1)} 0" rpy="${pi/2} ${pi/2} 0"/>
                <geometry>
                    <cylinder radius="0.029999999" length="0.1000000"/>
                </geometry>
                <material name="Gray">
                    <color rgba="0.5 0.5 0.5 1.0"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.029999999" length="0.10000000"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
        </link>

        <joint name="front_${prefix}_wheel_steering_joint" type="revolute">
            <parent link="base_link"/>
            <child link="front_${prefix}_steering_wheel_link"/>
            <origin xyz="${x_reflect * wheel_xoff} ${y_reflect * (base_width / 2 + wheel_ygap)} 0" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <limit effort="1000.0" lower="-0.698" upper="0.698" velocity="0.5"/>
        </joint>
    </xacro:macro>

    <xacro:steering_wheel prefix="left" x_reflect="1" y_reflect="1"/>
    <xacro:steering_wheel prefix="right" x_reflect="1" y_reflect="-1"/>

    <!-- Front Wheels -->
    <xacro:macro name="frontwheel" params="prefix x_reflect y_reflect">
        <link name="front_${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="Gray">
                    <color rgba="0.5 0.5 0.5 1.0"/>
                </material>
            </visual>
            <collision>
                <!-- <origin xyz="0 0 0" rpy="${pi/2} 0 0"/> -->
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>

            <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>
        </link>

        <joint name="front_${prefix}_wheel_joint" type="revolute">
            <parent link="front_${prefix}_steering_wheel_link"/>
            <child link="front_${prefix}_wheel"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <limit effort="1000.0" lower="-0.698" upper="0.698" velocity="0.5"/>
        </joint>
    </xacro:macro>

    <xacro:frontwheel prefix="left" x_reflect="1" y_reflect="1"/>
    <xacro:frontwheel prefix="right" x_reflect="1" y_reflect="-1"/>
        <!-- virtual front wheel -->

    <link name="virtual_front_wheel">
    <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
        <geometry>
        <cylinder length="0.01" radius="${wheel_radius}"/>
        </geometry>
        <material name="invisible"/>
    </visual>
    </link>

    <joint name="virtual_front_wheel_joint" type="revolute">
    <parent link="base_link"/>
    <child link="virtual_front_wheel"/>
    <origin xyz="${wheel_xoff} 0 0" rpy="0 0 ${pi/2}"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.7853" upper="0.7853" effort="100.0" velocity="100.0"/>
    <dynamics damping="0.2"/>
    </joint>

    <!-- virtual rear wheel -->
    <link name="virtual_rear_wheel">
    <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
        <geometry>
        <cylinder length="0.01" radius="${wheel_radius}"/>
        </geometry>
        <material name="invisible"/>
    </visual>
    </link>

    <joint name="virtual_rear_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="virtual_rear_wheel"/>
    <origin xyz="${-wheel_xoff} 0 0" rpy="0 0 ${pi/2}"/>
    <axis xyz="1 0 0"/>
    <limit effort="100.0" velocity="100.0"/>
    <dynamics damping="0.2"/>
    </joint>

    <!-- Lidar -->
    <link name="velodyne">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius=".0762" length=".0762"/>
            </geometry>
            <material name="Cyan">
                <color rgba="0 1.0 1.0 1.0"/>
            </material>
        </visual>
    </link>

    <joint name="velodyne_joint" type="fixed">
        <parent link="base_link"/>
        <child link="velodyne"/>
        <origin xyz="0 0 1.0414" rpy="0 0 0"/>
    </joint>
</robot>
