controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      linear_velocity_limit: 1.0
      angular_velocity_limit: 1.0
      min_turning_radius: 0.5
