amcl:
  ros__parameters:
    use_sim_time: false
    base_frame_id: base_link
    odom_frame_id: odom
    scan_topic: scan
    set_initial_pose: true

controller_server:
  ros__parameters:
    use_sim_time: false
    cmd_vel_topic: /nav_cmd_vel
    robot_base_frame: base_link
    odom_topic: odom

planner_server:
  ros__parameters:
    use_sim_time: false

bt_navigator:
  ros__parameters:
    use_sim_time: false

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""  # if using saved map
