navsat_transform:
  ros__parameters:
    frequency: 10.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_utm_transform: true
    publish_filtered_gps: true

    use_odometry_yaw: false
    use_imu_heading: true
    wait_for_datum: false
    use_manual_datum: false

    gps_topic: /gnss
    imu0: /imu/data
    odometry_topic: /bic_cont/odometry
