slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_mode: "mapping"
    resolution: 0.05
    map_update_interval: 5.0
    publish_tf: false
    odom_frame: "odom"
    base_frame: "base_link"
    map_frame: "map"
