twist_mux:
  ros__parameters:
    use_stamped: true  # <-- ✅ REQUIRED for Jazzy
    topics:
      keyboard:
        topic: /cmd_vel
        timeout: 0.5
        priority: 90
      navigation:
        topic: /nav/cmd_vel
        timeout: 0.5
        priority: 30
      simulatorchair:
        topic: /simulator_chair/cmd_vel
        timeout: 0.5
        priority: 80
