twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : /nav/cmd_vel
        timeout : 0.5
        priority: 30
      keyboard:
        topic   : /cmd_vel
        timeout : 0.5
        priority: 90
      simulatorchair:
        topic   : /simulator_chair/cmd_vel
        timeout : 0.5
        priority: 80
